In [3]:
import numpy as np

i = np.array([10, 20, 30, 40, 50])    # 1-D Element

print(i.shape)

(5,)


In [5]:
import numpy as np

i = np.array([
    [10, 20, 30, 40, 50],
    [60,70,80,90,100]])           # 2-D Element

print(i.shape)

(2, 5)


In [7]:
import numpy as np

i = np.array([
 [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]],
 [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]]
 ])                                                                # 3-D Element

print(i.shape)

(2, 3, 5)


In [9]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

j = i.reshape(5,2)                   # reshaping data 1-D to 2-D

j

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [11]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,
130, 140,150, 160])

j = i.reshape(2,2,4)                  # reshaping data 1-D to 3-D

j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [13]:
import numpy as np

i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,
130, 140,150,160])

j = i.reshape(2,4,-1)                   # Unknown Dimension 

j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [14]:
import numpy as np

i = np.array([
    [[10, 20, 30], [40, 50, 60]],
    [[70, 80, 90], [100, 110, 120]],
    [[130, 140,150],[1,2,3]]
])

j = i.reshape(-1)            #Multidimension

j

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150,   1,   2,   3])